// <auto-generated />
using System;
using AGUIWebChat.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AGUIWebChatServer.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    partial class QuizDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("AGUIWebChat.Server.Data.Entities.AnswerOptionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionCardId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestionCardId");

                    b.ToTable("AnswerOptions");
                });

            modelBuilder.Entity("AGUIWebChat.Server.Data.Entities.QuestionCardEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectAnswerDisplayJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectAnswerIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuizId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuizId", "Sequence");

                    b.ToTable("QuestionCards");
                });

            modelBuilder.Entity("AGUIWebChat.Server.Data.Entities.QuizAttemptEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<string>("SelectedAnswerIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAt");

                    b.HasIndex("CardId");

                    b.HasIndex("SessionId");

                    b.ToTable("QuizAttempts");
                });

            modelBuilder.Entity("AGUIWebChat.Server.Data.Entities.QuizEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Title");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("AGUIWebChat.Server.Data.Entities.QuizEvaluationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrectAnswerIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Feedback")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EvaluatedAt");

                    b.HasIndex("SubmissionId")
                        .IsUnique();

                    b.ToTable("QuizEvaluations");
                });

            modelBuilder.Entity("AGUIWebChat.Server.Data.Entities.QuizSessionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuizId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("QuizSessions");
                });

            modelBuilder.Entity("AGUIWebChat.Server.Data.Entities.QuizSubmissionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuizId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedAnswerIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("QuizId");

                    b.HasIndex("SubmittedAt");

                    b.HasIndex("UserId");

                    b.ToTable("QuizSubmissions");
                });

            modelBuilder.Entity("AGUIWebChat.Server.Data.Entities.AnswerOptionEntity", b =>
                {
                    b.HasOne("AGUIWebChat.Server.Data.Entities.QuestionCardEntity", "QuestionCard")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionCard");
                });

            modelBuilder.Entity("AGUIWebChat.Server.Data.Entities.QuestionCardEntity", b =>
                {
                    b.HasOne("AGUIWebChat.Server.Data.Entities.QuizEntity", "Quiz")
                        .WithMany("Cards")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("AGUIWebChat.Server.Data.Entities.QuizAttemptEntity", b =>
                {
                    b.HasOne("AGUIWebChat.Server.Data.Entities.QuestionCardEntity", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AGUIWebChat.Server.Data.Entities.QuizSessionEntity", "Session")
                        .WithMany("Attempts")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AGUIWebChat.Server.Data.Entities.QuizEvaluationEntity", b =>
                {
                    b.HasOne("AGUIWebChat.Server.Data.Entities.QuizSubmissionEntity", "Submission")
                        .WithOne("Evaluation")
                        .HasForeignKey("AGUIWebChat.Server.Data.Entities.QuizEvaluationEntity", "SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("AGUIWebChat.Server.Data.Entities.QuizSessionEntity", b =>
                {
                    b.HasOne("AGUIWebChat.Server.Data.Entities.QuizEntity", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("AGUIWebChat.Server.Data.Entities.QuestionCardEntity", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("AGUIWebChat.Server.Data.Entities.QuizEntity", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("AGUIWebChat.Server.Data.Entities.QuizSessionEntity", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("AGUIWebChat.Server.Data.Entities.QuizSubmissionEntity", b =>
                {
                    b.Navigation("Evaluation");
                });
#pragma warning restore 612, 618
        }
    }
}
